Repository performous/performous, pull requests merged in 2021-08, with the labels that each got.

#649 Removed unused defines from config.cmake.hh
  game/config.cmake.hh
Labels: Needs Testing, Cleanup, Ready For Review

#656 Re enabled ppa
  .semaphore/semaphore.yml
Labels: In Progress

#663 Fix keyboard instrument/nav keys getting stuck if released while holding mod keys
  game/controllers-keyboard.cc
Labels: Needs Testing
