Repository performous/performous, pull requests merged in 2021-09, with the labels that each got.

#664 Move video FFMPEG init back to thread
  game/video.cc
Labels: Needs Testing, Ready For Review

#655 Audio devices screen fixes and several cleanups in audio.cc and image.hh
  game/audio.cc
  game/image.hh
  game/screen_audiodevices.cc
Labels: Enhancement, Ready For Review

#653 Pitchwave order
  game/notegraph.cc
Labels: Ready For Review

#670 Added Kamina's PPA to meson builds
  .semaphore/semaphore.yml
Labels: Ready For Review

#675 Fix vsredist libraries
  CMakeLists.txt
Labels: Ready For Review

#681 Fixed duplicate songs on windows
  data/config/schema.xml
Labels: Needs Testing, Ready For Review
