Repository performous/performous, pull requests merged in 2022-04, with the labels that each got.

#706 Fix year within the license
  LICENSE.md
Labels: Ready For Review

#711 Updated vcpkg baseline, so we have build support with VS2022
  vcpkg.json
Labels: Ready For Review

#735 Removal of the semaphore build system since we use GH-Actions now
  .semaphore/project.yml
  .semaphore/semaphore.yml
Labels: Cleanup, Maintenance, Quality Assurance, Ready For Review

#676 Get rid of audiokiller.
  game/audio.cc
  game/libda/portaudio.hpp
Labels: Needs Testing, Ready For Review

#737 Fixes an uninitialized variable runtime error in debug mode
  game/guitargraph.cc
Labels: Ready For Review

#734 Remove experimental meson build support
  meson.build
  meson_options.txt
  subprojects/ced.wrap
Labels: Cleanup, Ready For Review

#745 Initialize and destroy Portaudio once
  game/audio.cc
  game/audio.hh
Labels: Needs Testing
