Repository performous/performous, pull requests merged in 2022-05, with the labels that each got.

#749 Removed SDL2 module since SDL2 comes with its own module these days
  cmake/Modules/FindSDL2.cmake
Labels: Needs Testing, Ready For Review

#748 Fixes a problem where localization wasn't functioning without make install
  lang/CMakeLists.txt
Labels: Needs Testing, Ready For Review

#756 Fix a breaking change in ubuntu 1804 docker image
  .github/workflows/build_and_release.yml
Labels: Regression / Toolchain Problem, Ready For Review

#732 Adds debian to the build pipeline
  .github/workflows/build_and_release.yml
  README.md
Labels: Needs Testing, Ready For Review

#765 Don't include libasound2 in appimage
  AppImageBuilder.yml
Labels: Needs Testing
